Vagrant.configure("2") do |config|
  config.vm.define "controller" do |controller|
    controller.vm.hostname = "controller"
    controller.vm.box = "ubuntu/bionic64"
    controller.vm.network "private_network", ip: "192.168.50.2"
    
    controller.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y software-properties-common
      sudo apt-add-repository --yes --update ppa:ansible/ansible
      sudo apt-get install -y ansible
    SHELL

    controller.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
    end

    config.vm.boot_timeout = 600  # Increase the boot timeout to 600 seconds
  end

  config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
  config.vm.usable_port_range = (8000..9000)
end
